sudo: false

language: php

php:
- 7.0

env:
  global:
  - DATABASE_USER=travis DATABASE_HOST=localhost DATABASE_PORT=3306 DATABASE_NAME=typo3 DATABASE_PASSWORD=''
  - TYPO3_PATH_ROOT=$PWD/.Build/public
  matrix:
  - TYPO3_VERSION="^7.6"

matrix:
  exclude:

cache:
  directories:
  - .Build/vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini

install:
- >
  composer require typo3/minimal=$TYPO3_VERSION;
  if [ "$TYPO3_VERSION" == "^8.7" ]; then
    composer require pagemachine/typo3-composer-legacy-cli;
  fi;
  composer show;
- >
  .Build/vendor/bin/typo3cms install:setup --non-interactive --site-setup-type="site"
  --database-user-name="${DATABASE_USER}" --database-host-name="${DATABASE_HOST}"
  --database-port="${DATABASE_PORT}" --database-name="${DATABASE_NAME}"
  --admin-user-name="admin" --admin-password="password" --site-name="Test installation";
- >
  echo;
  echo "Restoring the composer.json";
  git checkout .;

before_script:
- mysql -u ${DATABASE_USER} ${DATABASE_NAME} -e "INSERT INTO be_users (username, password) VALUES ('_cli_phpunit', 'password')"

script:
- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;
- >
  echo;
  echo "Running the unit tests";
  composer ci:tests:unit;
- >
  echo;
  echo "Running the functional tests";
  composer ci:tests:functional;
