sudo: false

language: php

php:
- 7.0

env:
- TYPO3_VERSION="^7.6"

matrix:
  exclude:

cache:
  directories:
  - .Build/vendor
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini

install:
- >
  composer require typo3/minimal=$TYPO3_VERSION;
  if [ "$TYPO3_VERSION" == "^8.7" ]; then
    composer require pagemachine/typo3-composer-legacy-cli;
  fi;
  composer show;
- >
  echo;
  echo "Restoring the composer.json";
  git checkout .;
- >
  export TYPO3_PATH_ROOT=$PWD/.Build/public;

script:
- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;
