os: linux

# We can switch to "bionic" once we have dropped support for PHP 7.0.
dist: xenial

language: php

addons:
  apt:
    packages:
      - parallel

services:
  - mysql

env:
  global:
  - DATABASE_USER=travis DATABASE_HOST=localhost DATABASE_PORT=3306 DATABASE_NAME=typo3 DATABASE_PASSWORD=''
  - typo3DatabaseUsername=travis typo3DatabaseHost=localhost typo3DatabaseName=typo3 typo3DatabasePassword=''

cache:
  directories:
  - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
- >
  composer require typo3/minimal:"$TYPO3";
  composer show;
- >
  .Build/vendor/bin/typo3cms install:setup --no-interaction --site-setup-type="site"
  --database-user-name="${DATABASE_USER}" --database-host-name="${DATABASE_HOST}"
  --database-port="${DATABASE_PORT}" --database-name="${DATABASE_NAME}"
  --admin-user-name="admin" --admin-password="password" --site-name="Test installation";
- >
  echo;
  echo "Restoring the composer.json";
  git checkout .;

script:
- >
  echo;
  echo "Linting all PHP files";
  composer ci:php:lint;
- >
  echo;
  echo "Running PHP_CodeSniffer";
  composer ci:php:sniff;
- >
  echo;
  echo "Running PHP-CS-Fixer";
  composer ci:php:fixer;
- >
  echo;
  echo "Linting all TypoScript files";
  composer ci:ts:lint;
- >
  echo;
  echo "Running the unit tests";
  composer ci:tests:unit;
- >
  echo;
  echo "Running the legacy unit tests";
  composer ci:tests:unit-legacy;
- >
  echo;
  echo "Running the functional tests";
  composer ci:tests:functional;

jobs:
  include:
  - stage: test
    php: "7.2"
    env: TYPO3=^9.5
  - stage: test
    php: "7.2"
    env: TYPO3=^8.7
  - stage: test
    php: "7.1"
    env: TYPO3=^8.7
  - stage: test
    php: "7.0"
    env: TYPO3=^8.7
  - stage: release to ter
    if: tag IS present AND env(TYPO3_ORG_USERNAME) IS present AND env(TYPO3_ORG_PASSWORD) IS present
    php: "7.2"
    before_install: skip
    install: skip
    before_script: skip
    script:
    - >
      echo;
      echo "Preparing upload of release ${TRAVIS_TAG} to TER";
      echo;
      echo;
      composer global require helhum/ter-client;
    - >
      echo;
      echo "Removing development-only files";
      echo;
      echo;
      rm -rf CODE_OF_CONDUCT.md Resources/Private/Php/update.sh Tests/;
    - >
      TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
      echo;
      echo "Uploading release ${TRAVIS_TAG} to TER";
      echo;
      echo;
      $HOME/.composer/vendor/bin/ter-client upload seminars . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
