services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OliverKlee\Seminars\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*,../Classes/Model/*,../Classes/OldModel/*,../Classes/Service/SingleViewLinkBuilder.php'
